---
title: "Dimensions of Statistical Graphics"
subtitle: Participant Consent
project:
  output-dir: ./www
  post-render: post-render.sh
format: 
  pdf:
    number-sections: false
  html:
    number-sections: false
---

## Study Information

**IRB Project ID #**: 22579

**Project Title**: Exploration of Statistical Graphics and Experiential Learning

**Contact Information**:

- Project Questions: Dr. Susan Vanderplas at susan.vanderplas@unl.edu.

- If you have questions about your rights or complaints about the research, contact the UNL Institutional Review Board (IRB) at (402) 472-6965 or irb@unl.edu.


## Overview

**Purpose**: The purpose of this research is to understand how we perceive statistical graphics and how accurately we can read information from charts represented in different ways.

**Time**: This survey should take less than 20 minutes to complete.

**Eligibility**: You may participate in this research if you are a student in Stat 218.

**Risks and Benefits**

- There are no risks to participation in this research.
- There are no benefits to you directly as a participant in this research.
- Society may benefit by understanding how people read and use charts and data, which will help scientists communicate better with the general public.

## Data and Privacy

Quick Summary: 

- We are not collecting any data which can be traced back to you during this study.

- We will publish the dataset from this survey in full online to ensure that other researchers can see how we obtained our results.

- You will be given a code at the end of the study to prove you completed the survey for Stat 218. You do not have to agree to allow your responses to be used for research purposes in order to get the code. This code will not be associated with your responses to this survey.

--------

Reasonable steps will be taken to protect the privacy and the confidentiality of your study data; however, in some circumstances we cannot guarantee absolute privacy and/or confidentiality.

Your responses to this experiment will be stored in de-identified form and will not be able to be traced back to you. 
Because this data is anonymous, it will be stored and maintained in accordance with university policies for low-risk data.
All study records will be maintained on UNL servers for at least 3 years after the completion of the study in accordance with UNL HRPP 2018 Policy #3.013 section 2.3.A. 

**Data Sharing and Publication**

Data from this experiment may be published along with computer code describing the analysis and any study results in order to ensure the reproducibility of any analyses performed as part of this research. 
This data is anonymous - it cannot be traced back to you. 
The researchers will also archive the data for this study on the UNL Data Repository, where it will be preserved indefinitely and made publicly available.


## Study Participation

You can decide to not allow your responses to be used for research purposes by declining to participate in this research study (select "I do not agree" below). 
This will prevent your data from being *recorded* and used for research, but you will still be able to see the study questions and provide responses. 
You will still get a completion code at the end of the study, even if you decline to participate.
The only difference is that your data will not be saved or used for research.


You can decide not to be in this research study, or you can withdraw at any time before or during the study for any reason. 
Deciding not to be in this research study or deciding to withdraw will not affect your relationship with the investigator, the University of Nebraska-Lincoln, or (if you are a Stat 218 student) your Stat 218 instructor. 
You will not lose any benefits to which you are entitled.


You are voluntarily making a decision whether or not to participate in this research study. 
By clicking on the I Agree button below, your consent to participate is implied. 
You should print or save a copy of this page for your records. 

::: {.content-visible unless-format="pdf"}
<a href="https://github.com/TWiedRW/3d_graphical_perception/raw/main/experiment_interface/www/graphics-consent-218.pdf" target="_blank">Link to PDF copy of the consent form</a>
:::